# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "StefanScherer/windows_10"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.linked_clone = true
    vb.memory = "3072"
  end

  config.vm.provision "shell", path: "/home/wosi/Scripts/PSConfEU2018-presentations/PSConfEU2018-presentation-Ansible/Demo-1/ConfigureRemotingForAnsible.ps1", privileged: true
  
end
